#ifndef _PLAT_IRQ_H_
#define _PLAT_IRQ_H_

enum irqchip_id {
	IRQCHIP_GIC,

	__NR_IRQCHIP,
};

enum irq_id {
	__GIC_IRQ_ID_OFS = 0,
	IRQ_SGI_START = __GIC_IRQ_ID_OFS,
	IRQ_SGI_END = 15,
	IRQ_PPI_VIRT_MAINTAIN = 25,
	IRQ_PPI_HYP_TIMER,
	IRQ_PPI_VIRT_TIMER,
	IRQ_PPI_LEGACY_FIQ,
	IRQ_PPI_SECURE_TIMER,
	IRQ_PPI_NON_SECURE_TIMER = 30,
	IRQ_PPI_LEGACY_IRQ,
	IRQ_UART = 33,
	IRQ_RTC,
	IRQ_PCIE_0 = 35,
	IRQ_PCIE_1,
	IRQ_PCIE_2,
	IRQ_PCIE_3,
	IRQ_GPIO,
	IRQ_SECURE_UART = 40,
	IRQ_ACPI_GED,

	__NR_IRQ,
};

enum gic_irq_id {
	GIC_SGI_START = 0,
	GIC_SGI_END = 15,
	GIC_PPI_VIRT_MAINTAIN = 25,
	GIC_PPI_HYP_TIMER,
	GIC_PPI_VIRT_TIMER,
	GIC_PPI_LEGACY_FIQ,
	GIC_PPI_SECURE_TIMER,
	GIC_PPI_NON_SECURE_TIMER = 30,
	GIC_PPI_LEGACY_IRQ,
	GIC_IRQ_UART = 33,
	GIC_IRQ_RTC,
	GIC_IRQ_PCIE_0 = 35,
	GIC_IRQ_PCIE_1,
	GIC_IRQ_PCIE_2,
	GIC_IRQ_PCIE_3,
	GIC_IRQ_GPIO,
	GIC_IRQ_SECURE_UART = 40,
	GIC_IRQ_ACPI_GED,

	__NR_GIC_IRQ,
};
#endif /* _PLAT_IRQ_H_ */
